### ISSUE TITLE
A bug in ch_sparsity_dict 

### ISSUE THREAD

**Issue by YuxuanDuan** [VainF/Torch-Pruning#107]
I trial to pass a ch_sparsiity_dict to tp.pruner.MagnitudePruner(). However , it returns me this:
`Traceback (most recent call last):
  File "D:\anaconda3\envs\pytorch-gpu\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-453e39af4c66>", line 1, in <module>
    isinstance(submodule, prunable_types)
TypeError: isinstance() arg 2 must be a type or tuple of types`

So I think prunable_types should be a tuple rather than list. And after I change it, it got right

**Comment by VainF** [comment]
Fixed. Thank you!
