### ISSUE TITLE
Issue about pruning YoloV7

### ISSUE THREAD

**Issue by shadowpa0327** [VainF/Torch-Pruning#151]
Hi, thanks first for the great work!  Currently, I am trying to prune the yolov7 and conduct the finetune. I use the training code you provide in `/benchmarks/prunability/yolov7_train_pruned.py` and run into the following error:

```
Traceback (most recent call last):
  File "yolov7_train_pruned.py", line 655, in <module>
    train(hyp, opt, device, tb_writer)
  File "yolov7_train_pruned.py", line 131, in train
    pruner.step()
  File "/home/shadowpa0327/.local/lib/python3.8/site-packages/torch_pruning/pruner/algorithms/metapruner.py", line 159, in step
    for group in self.prune_local():
  File "/home/shadowpa0327/.local/lib/python3.8/site-packages/torch_pruning/pruner/algorithms/metapruner.py", line 201, in prune_local
    for group in self.DG.get_all_groups(ignored_layers=self.ignored_layers, root_module_types=self.root_module_types):
  File "/home/shadowpa0327/.local/lib/python3.8/site-packages/torch_pruning/dependency.py", line 466, in get_all_groups
    for m in self.module2node.keys():
RuntimeError: dictionary keys changed during iteration
``


Could author provide some hint or information on how to debug? Thanks !

**Comment by VainF** [comment]
fixed in the latest version. Please clone the latest version. thank you!

**Comment by shadowpa0327** [comment]
Thanks you so much for the rapid response!  After the update the pruned model can be generated sucessfully. 
However, when I start finetuning, it seems there is some error in CUDA
```
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1894,0,0], thread: [11,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1894,0,0], thread: [57,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1894,0,0], thread: [58,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1894,0,0], thread: [59,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1894,0,0], thread: [60,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1894,0,0], thread: [61,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1894,0,0], thread: [62,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1894,0,0], thread: [63,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [3503,0,0], thread: [119,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1562,0,0], thread: [3,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [3196,0,0], thread: [102,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
```

Have you ever face similar issue before?

**Comment by VainF** [comment]
Hi @shadowpa0327, My training looks good.

<img width="814" alt="image" src="https://user-images.githubusercontent.com/18592211/232128403-e60866fe-9aac-42c9-b2c4-fdb2c517bc1a.png">

My environment:
```
pytorch==1.12.1
torchvision==0.13.1
```

**Comment by shadowpa0327** [comment]
@VainF  Thanks you so much for the response. The update is verified and training work well. 

The error above was the bug in my own implementation, it is cause by the error of the output dimension. 

For those user that is going to extend YOLO model to multi-task, please don't forget to add the corresponding into the `ignore_layer`

Finally, thanks for the great and excellent framework, great job!

**Comment by VainF** [comment]
Thank you for this issue too. It would be helpful for other users!
