### ISSUE TITLE
 AttributeError: 'NoneType' object has no attribute 'data' in Torch Pruning

### ISSUE THREAD

**Issue by John1231983** [VainF/Torch-Pruning#217]
I am attempting to perform pruning for ppipnet (https://github.com/jhb86253817/PIPNet). I used version 1.1.19 of torch pruning, but I encountered an error. How can I correct it? Here is my code:
```
    dummy_inputs = torch.randn(1, 3, 256, 256).cuda()
    imp = tp.importance.TaylorImportance()

    ignored_layers = []  # Add the head layer to the ignored_layers list
    # ignore output layers
    for m in model.modules():
        if isinstance(m, torch.nn.Linear) and m.out_features == 136:
            ignored_layers.append(m)
        elif isinstance(m, torch.nn.modules.conv._ConvNd) and m.out_channels == 136:
            ignored_layers.append(m)
    
    print (ignored_layers)
    iterative_steps = 5 # progressive pruning
    pruner = tp.pruner.MagnitudePruner(
        landmark_model,
        dummy_inputs,
        importance=imp,
        iterative_steps=iterative_steps,
        ch_sparsity=0.5, # remove 50% channels, ResNet18 = {64, 128, 256, 512} => ResNet18_Half = {32, 64, 128, 256}
        ignored_layers=ignored_layers,
    )
    base_macs, base_nparams = tp.utils.count_ops_and_params(model, dummy_inputs)
    print (base_macs, base_nparams)
    
    # Start purning model
    pruner.step()

    # Parameter & MACs Counter
    pruned_macs, pruned_nparams = tp.utils.count_ops_and_params(model, dummy_inputs)
   
```

This is my error
```
  pruner.step()
  File "/home/john/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_pruning/pruner/algorithms/metapruner.py", line 165, in step
    for group in self.prune_local():
  File "/home/john/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_pruning/pruner/algorithms/metapruner.py", line 214, in prune_local
    imp = self.estimate_importance(group, ch_groups=ch_groups)
  File "/home/john/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_pruning/pruner/algorithms/metapruner.py", line 169, in estimate_importance
    return self.importance(group, ch_groups=ch_groups)
  File "/home/john/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/john/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_pruning/importance.py", line 419, in __call__
    dw = layer.weight.grad.data[idxs].flatten(1)
AttributeError: 'NoneType' object has no attribute 'data'
```

**Comment by VainF** [comment]
Hi @John1231983, Taylor pruner relies on gradients for importance estimation. So please make sure there is ``loss.backward()`` before pruner.step().

**Comment by John1231983** [comment]
@VainF it solved. However, I got new issue with DP mode training. It worked without DP. This is code and error
```
 if train_mode == 'DP': # Data Parallel
        model = torch.nn.DataParallel(model, device_ids=cfg.gpu_list).cuda()
    else:
        model = model.cuda()
   
```
Thi is error
```
/home/john/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/_tensor.py:1083: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484772347/work/build/aten/src/ATen/core/TensorBody.h:482.)
  return self._grad
Traceback (most recent call last):
  File "train_pruning.py", line 278, in <module>
    main(parser.parse_args())
  File "train_pruning.py", line 204, in main
    progressive_pruning(pruner, landmark_model, speed_up=cfg.speed_up, example_inputs=dummy_inputs)
  File "train_pruning.py", line 31, in progressive_pruning
    pruner.step(interactive=False)
  File "/home/john/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_pruning/pruner/algorithms/metapruner.py", line 166, in step
    group.prune()
  File "/home/john/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_pruning/dependency.py", line 184, in prune
    root_module_name = self._DG._module2name[root_module]
KeyError: Conv2d(160, 45, kernel_size=(1, 1), stride=(1, 1))
```

**Comment by John1231983** [comment]
@VainF I got same error with sparsity step
This is my code
```
pruner = get_pruner(model, example_inputs=example_inputs)
optimizer.zero_grad()
 out = model(data)
 loss = F.cross_entropy(out, target)
 loss.backward()
 if pruner is not None:
        pruner.regularize(model) # for sparsity learning
```
The error is. Could you help me to fix the issue?
```
   main(parser.parse_args())
  pruner.regularize(model) # for sparsity learning
  File "/home/john/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/john/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_pruning/pruner/algorithms/group_norm_pruner.py", line 151, in regularize
    layer.weight.grad.data[idxs]+=self.reg * g
AttributeError: 'NoneType' object has no attribute 'data'
```

**Comment by John1231983** [comment]
OK. I found the issue. It is related to the issue of DP training
https://github.com/VainF/Torch-Pruning/issues/217#issuecomment-1637076031

**Comment by lebron-2016** [comment]
> OK. I found the issue. It is related to the issue of DP training [#217 (comment)](https://github.com/VainF/Torch-Pruning/issues/217#issuecomment-1637076031)

Hello,  what the issue of DP training?
