### ISSUE TITLE
torch.jit.trace of pruned model fails when L2Norm is involved

### ISSUE THREAD

**Issue by abuvaneswari** [VainF/Torch-Pruning#24]
Hello,

I used Torch_Pruning to prune [SSD](https://github.com/amdegroot/ssd.pytorch) model. 

Note that I use this fork:
https://github.com/dkurt/ssd.pytorch/tree/opencv_support

My onnx model works good - I can view it in netron and I can use it in Intel Openvino. There is a L2Norm layer that seems to follow the vgg layers and feeds into the conf.0 and loc.0 layers.

I used Torch-Pruning to prune away some of conv filters in the vgg layers. However, I get the following error when I run torch.jit.trace on the pruned model:

BEGIN: Torch jit of pruned model ************ 
Traceback (most recent call last):
  File "prune_TP_git_issue.py", line 62, in <module>
    model_output = torch.jit.trace(model, torch_image)
  File "/home/tfs/venv_ssd.pytorch/lib/python3.6/site-packages/torch/jit/__init__.py", line 882, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/home/tfs/venv_ssd.pytorch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1034, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
  File "/home/tfs/venv_ssd.pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/tfs/venv_ssd.pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/nas4/tfs/ssd.pytorch/ssd.py", line 94, in forward
    s = self.L2Norm.weight.view(1, -1, 1, 1) * x
RuntimeError: The size of tensor a (512) must match the size of tensor b (256) at non-singleton dimension 1

Here is the code that performs the pruning:

`
import argparse
import torch
import torch.nn as nn
import os
from ssd import build_ssd
import sys
import time
import torch_pruning as tp
import numpy as np
BASE = 2
SPARSITY = 0.5

if __name__ == '__main__':
    parser = argparse.ArgumentParser('Prune trained model')
    parser.add_argument('--model', required=True, help='Path to saved PyTorch network weights (*.pth)')
    parser.add_argument('--size', default=300, help='Input resolution')
    parser.add_argument('--num_classes', default=21, help='Number of trained classes + 1 for background')
    args = parser.parse_args()

    device = 'cpu'
    net = build_ssd('export', args.size, args.num_classes)
    net.load_state_dict(torch.load(args.model, map_location='cpu'))
    net.eval()

    model = net

    img = torch.randn((1, 3, args.size, args.size), device=device)
    dummy_input = img
    print ("device = ", device)

    torch_image = img

    DG = tp.DependencyGraph().build_dependency( model, torch_image)
    def prune_conv(conv, pruned_prob):
        weight = conv.weight.detach().cpu().numpy()
        out_channels = weight.shape[0]
        L1_norm = np.sum( np.abs(weight), axis=(1,2,3))
        num_pruned = int(out_channels * pruned_prob)
        print("======== prune_conv() ========")
        print("Proposed num_pruned = ", num_pruned)
        prune_index = np.argsort(L1_norm)[:num_pruned].tolist() # remove filters with small L1-Norm
        print("prune_index = ", prune_index)
        plan = DG.get_pruning_plan(conv, tp.prune_conv, prune_index)
        plan.exec()

    for m in model.modules():        
        for name, mm in m.named_children():
            print("LEVEL 1 : ", name, mm)
            if 'vgg' not in name:
                continue
            for name2, mm2 in mm.named_children():
                print("____ LEVEL 2 : ", name2, mm2)
                if isinstance(mm2, nn.Conv2d) :
                    print("Conv2d detected. Attempting to prune......")
                    prune_conv(mm2, SPARSITY)
                print("____ END CHILD LEVEL 2 ______________________")
    print("BEGIN: Torch jit of pruned model ************ ")
    model_output = torch.jit.trace(model, torch_image)
    print("Torch jit of pruned model succeeded *********** ")
'

**Comment by VainF** [comment]
Hi @abuvaneswari

L2Norm is a customized layer and thus not supported in this repo. I'm working on this to support customized ops and rules.

**Comment by VainF** [comment]
Please refer to "examples/customized_layer.py". A detailed tutorial will be uploaded soon.

**Comment by abuvaneswari** [comment]
@VainF , thanks a lot! Your example and the latest commits were extremely helpful. Now the jit trace succeeds!
