### ISSUE TITLE
Mismatch shape when prunning yolov7 with GroupNorm?

### ISSUE THREAD

**Issue by aidevmin** [VainF/Torch-Pruning#268]
I follow your guide @VainF to prune yolov7, but I modified with GroupNorm `imp = tp.importance.GroupNormImportance(p=2)` and `tp.pruner.GroupNormPruner` without sparse training, but I got an mismatch shape error as follow
```
Traceback (most recent call last):
  File "yolov7_train_pruned_GroupNorm_woSL.py", line 684, in <module>
    train(hyp, opt, device, tb_writer)
  File "yolov7_train_pruned_GroupNorm_woSL.py", line 157, in train
    pruner.step()
  File "/usr/local/lib/python3.8/dist-packages/torch_pruning/pruner/algorithms/metapruner.py", line 153, in step
    for group in self.prune_global():
  File "/usr/local/lib/python3.8/dist-packages/torch_pruning/pruner/algorithms/metapruner.py", line 242, in prune_global
    imp = self.estimate_importance(group, ch_groups=ch_groups)
  File "/usr/local/lib/python3.8/dist-packages/torch_pruning/pruner/algorithms/metapruner.py", line 163, in estimate_importance
    return self.importance(group, ch_groups=ch_groups)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch_pruning/importance.py", line 264, in __call__
    group_norm += local_norm
RuntimeError: The size of tensor a (512) must match the size of tensor b (2048) at non-singleton dimension 0
```
Please check it again.

**Comment by aidevmin** [comment]
@VainF 
Please support me.

**Comment by VainF** [comment]
Hi @aidevmin, this [example](https://github.com/VainF/Torch-Pruning/blob/master/examples/yolov7/yolov7_detect_pruned.py) works well on my side. Please try to ignore the whole Detect layer during pruning.

```python
for m in model.modules():
    if isinstance(m, (Detect,IDetect)):
        ignored_layers.append(m)
```

**Comment by aidevmin** [comment]
@VainF 
Thanks. It worked for me.
