### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by wujianfei5201314** [VainF/Torch-Pruning#277]
Traceback (most recent call last):
  File "D:\yolov81010\test1.py", line 440, in <module>
    prune(args)
  File "D:\yolov81010\test1.py", line 369, in prune
    pruner = tp.pruner.GroupNormPruner(
  File "D:\LenovoSoftstore\anaconda\envs\yolov8717\lib\site-packages\torch_pruning\pruner\algorithms\group_norm_pruner.py", line 82, in __init__
    self._groups = list(self.DG.get_all_groups(root_module_types=self.root_module_types, ignored_layers=self.ignored_layers))
  File "D:\LenovoSoftstore\anaconda\envs\yolov8717\lib\site-packages\torch_pruning\dependency.py", line 519, in get_all_groups
    group = self.get_pruning_group(
  File "D:\LenovoSoftstore\anaconda\envs\yolov8717\lib\site-packages\torch_pruning\dependency.py", line 477, in get_pruning_group
    _fix_dependency_graph_non_recursive(*group[0])
  File "D:\LenovoSoftstore\anaconda\envs\yolov8717\lib\site-packages\torch_pruning\dependency.py", line 463, in _fix_dependency_graph_non_recursive
    new_indices = mapping(new_indices)
  File "D:\LenovoSoftstore\anaconda\envs\yolov8717\lib\site-packages\torch_pruning\_helpers.py", line 91, in __call__
    new_idxs = [ _HybridIndex(idx=i.idx + self.offset[0], root_idx=i.root_idx) for i in idxs]
  File "D:\LenovoSoftstore\anaconda\envs\yolov8717\lib\site-packages\torch_pruning\_helpers.py", line 91, in <listcomp>
    new_idxs = [ _HybridIndex(idx=i.idx + self.offset[0], root_idx=i.root_idx) for i in idxs]
IndexError: list index out of range

Process finished with exit code 1

**Comment by zmeng12** [comment]
请问有解决吗

**Comment by Sarthak-22** [comment]
Hi, were you able to solve it ?

**Comment by Christian-lyc** [comment]
I find it's weird, on my laptop, it can run, but when I switch to server, this error occurs.
