### ISSUE TITLE
IndexError: index 512 is out of bounds for dimension 0 with size 512

### ISSUE THREAD

**Issue by Minspeech** [VainF/Torch-Pruning#299]
Thank you for your great work!
I encountered the following problem when reproducing pruning. What happened?

Traceback (most recent call last):
  File "prune_hf_wav2vec.py", line 68, in <module>
    for g in pruner.step(interactive=True):
  File "/root/anaconda3/envs/hugface2/lib/python3.8/site-packages/torch_pruning/pruner/algorithms/metapruner.py", line 347, in prune_local
    imp = self.estimate_importance(group, ch_groups=ch_groups)
  File "/root/anaconda3/envs/hugface2/lib/python3.8/site-packages/torch_pruning/pruner/algorithms/metapruner.py", line 234, in estimate_importance
    return self.importance(group, ch_groups=ch_groups)
  File "/root/anaconda3/envs/hugface2/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/hugface2/lib/python3.8/site-packages/torch_pruning/pruner/importance.py", line 218, in __call__
    w = layer.weight.data[idxs]
IndexError: index 512 is out of bounds for dimension 0 with size 512

**Comment by 644427434** [comment]
Hey！ I had a similar problem, have you solved it ？
