### ISSUE TITLE
Keyerror: MkldnnConvolutionBackward with 1D Layers

### ISSUE THREAD

**Issue by Richuo** [VainF/Torch-Pruning#4]
Hello,

I encountered an issue when trying to use pruning.DependencyGraph function with a CNN that has Conv1d, BatchNorm1d and F.avg_pool1d.

### CNN Class
```
class Conv1DNet(nn.Module):
    def __init__(self, num_classes=10):
        super(Conv1DNet, self).__init__()
 
        self.conv1 = nn.Conv1d(1, 64, kernel_size=3, stride=2, padding=1, bias=False)
        self.bn1 = nn.BatchNorm1d(64)
        self.linear = nn.Linear(512, num_classes)
 
    def forward(self, x):
        out = F.relu(self.bn1(self.conv1(x)))
        out = F.avg_pool1d(out, 2*16*281)
        feature = out.view(out.size(0), -1)
        out = self.linear(feature)
        return out
```

### Code run
```
model = Conv1DNet()

DG = pruning.DependencyGraph(model, fake_input=torch.randn(1,1, 144000))

pruning_plan = DG.get_pruning_plan(model.conv1, pruning.prune_conv, idxs=[2, 6, 9] )
print(pruning_plan)

pruning_plan.exec()
```

### Output
```
Traceback (most recent call last):
  File "issue_torch_pruning.py", line 27, in <module>
    DG = pruning.DependencyGraph(model, fake_input=torch.randn(1,1, 144000) )
  File "C:\Users\User\Anaconda3\envs\env-gpu\lib\site-packages\torch_pruning\dependency.py", line 186, in __init__
    self.build_dependency(model, fake_input)
  File "C:\Users\User1\Anaconda3\envs\env-gpu\lib\site-packages\torch_pruning\dependency.py", line 321, in build_dependency
    self._traverse_graph(out.grad_fn)
  File "C:\Users\User1\Anaconda3\envs\env-gpu\lib\site-packages\torch_pruning\dependency.py", line 437, in _traverse_graph
    _recursively_detect_dependencies(begin_node, 0)
  File "C:\Users\User1\Anaconda3\envs\env-gpu\lib\site-packages\torch_pruning\dependency.py", line 434, in _recursively_detect_dependencies
    _recursively_detect_dependencies(u[0], path_id)
  File "C:\Users\User1\Anaconda3\envs\env-gpu\lib\site-packages\torch_pruning\dependency.py", line 434, in _recursively_detect_dependencies
    _recursively_detect_dependencies(u[0], path_id)
  File "C:\Users\User1\Anaconda3\envs\env-gpu\lib\site-packages\torch_pruning\dependency.py", line 407, in _recursively_detect_dependencies
    node_module = self.grad_fn_to_module[node]
KeyError: <MkldnnConvolutionBackward object at 0x000001A1AE08B448>
```

Thanks for your help !

**Comment by VainF** [comment]
Hi @Richuo , please try the latest package (v0.2.1).
