### ISSUE TITLE
IndexError: index 1536 is out of bounds for dimension 0 with size 1024

### ISSUE THREAD

**Issue by broken-dream** [VainF/Torch-Pruning#412]
I'm trying to prune a ViT model implemented in [vit_pytorch](https://github.com/lucidrains/vit-pytorch) but got following error:
```
Traceback (most recent call last):
  File "/home/wh/generative_action/SynHSI/test_prune.py", line 30, in <module>
    for g in pruner.step(interactive=True):
  File "/home/wh/miniconda3/envs/hsi-torch-dev/lib/python3.10/site-packages/torch_pruning/pruner/algorithms/metapruner.py", line 411, in _prune
    imp = self.estimate_importance(group) # raw importance score
  File "/home/wh/miniconda3/envs/hsi-torch-dev/lib/python3.10/site-packages/torch_pruning/pruner/algorithms/metapruner.py", line 279, in estimate_importance
    return self.importance(group)
  File "/home/wh/miniconda3/envs/hsi-torch-dev/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/wh/miniconda3/envs/hsi-torch-dev/lib/python3.10/site-packages/torch_pruning/pruner/importance.py", line 221, in __call__
    local_imp = local_imp[idxs]
IndexError: index 1536 is out of bounds for dimension 0 with size 1024
```
From other similar issues, it seems this problem is caused by the `torch.split()` operation. But I didn't find any usage of `torch.split()` in vit_pytorch. 

I also tried to locate the problem by using `RandomImportance` mentioned in #147, but it works well when using `RandomImportance`.

BTW, when I used `RandomImportance` to prune the model, I found that the  parameter number of the model decreased but the inference time increased. I have no experience in model pruning so I have no idea if it's a normal phenomenon. But Intuitively fewer parameter should mean less time cost?

**Comment by VainF** [comment]
Hi check this example: https://github.com/VainF/Torch-Pruning/blob/d7e23ed28dded2b6208074977f18b6302bb8a46e/examples/transformers/prune_hf_vit.py#L102. A num_heads parameter is required for transformer pruning.
